/* Unit tests for agent/common, driven by the vectors generated by
 * docs/protocol/test-vectors/generate.py (an independent implementation). */
#include <stdio.h>
#include <string.h>

#include "ndp/ndp_agent.h"
#include "ndp/ndp_auth.h"
#include "ndp/ndp_frame.h"
#include "ndp/ndp_names.h"
#include "ndp/ndp_path.h"
#include "ndp/ndp_policy.h"
#include "ndp/ndp_sha256.h"
#include "ndp/ndp_tlv.h"
#include "vectors_gen.h"

static int g_checks = 0, g_fail = 0;

#define CHECK(cond, ...)                                                   \
  do {                                                                     \
    g_checks++;                                                            \
    if (!(cond)) {                                                         \
      g_fail++;                                                            \
      printf("  FAIL %s:%d: %s -- ", __FILE__, __LINE__, #cond);            \
      printf(__VA_ARGS__);                                                 \
      printf("\n");                                                        \
    }                                                                      \
  } while (0)

static void test_sha256(void) {
  int i;
  uint8_t d[32];
  ndp_sha256_ctx c;
  size_t k;
  static const uint8_t million_a[32] = {
      0xcd, 0xc7, 0x6e, 0x5c, 0x99, 0x14, 0xfb, 0x92, 0x81, 0xa1, 0xc7, 0xe2, 0x84, 0xd7, 0x3e, 0x67,
      0xf1, 0x80, 0x9a, 0x48, 0xa4, 0x97, 0x20, 0x0e, 0x04, 0x6d, 0x39, 0xcc, 0xc7, 0x11, 0x2c, 0xd0};
  for (i = 0; i < V_SHA_N; i++) {
    ndp_sha256(v_sha[i].msg, v_sha[i].msg_len, d);
    CHECK(memcmp(d, v_sha[i].digest, 32) == 0, "sha256 vector %d", i);
    /* one byte at a time must give the same digest */
    ndp_sha256_init(&c);
    for (k = 0; k < v_sha[i].msg_len; k++) ndp_sha256_update(&c, v_sha[i].msg + k, 1);
    ndp_sha256_final(&c, d);
    CHECK(memcmp(d, v_sha[i].digest, 32) == 0, "sha256 byte-wise vector %d", i);
  }
  { /* 1,000,000 x 'a' (FIPS 180 test) */
    uint8_t chunk[1000];
    memset(chunk, 'a', sizeof chunk);
    ndp_sha256_init(&c);
    for (k = 0; k < 1000; k++) ndp_sha256_update(&c, chunk, sizeof chunk);
    ndp_sha256_final(&c, d);
    CHECK(memcmp(d, million_a, 32) == 0, "sha256 million a");
  }
}

static void test_hmac(void) {
  int i;
  uint8_t d[32];
  for (i = 0; i < V_HMAC_N; i++) {
    ndp_hmac_sha256(v_hmac[i].key, v_hmac[i].key_len, v_hmac[i].msg, v_hmac[i].msg_len, d);
    CHECK(memcmp(d, v_hmac[i].mac, 32) == 0, "hmac vector %d", i);
  }
}

static void feed_all(ndp_decoder *d, const uint8_t *wire, size_t n, size_t step, int *frames, int *last_rc) {
  size_t pos = 0;
  while (pos < n) {
    size_t take = n - pos < step ? n - pos : step, used = 0;
    int rc = ndp_decoder_feed(d, wire + pos, take, &used);
    pos += used;
    *last_rc = rc;
    if (rc == NDP_DEC_FRAME) { (*frames)++; return; }
    if (rc == NDP_DEC_ERROR) return;
    if (used == 0) return;
  }
}

static void test_frames(void) {
  int i;
  static uint8_t buf[NDP_HEADER_SIZE + 65536 + NDP_MAC_SIZE], out[70000];
  for (i = 0; i < V_FRAMES_N; i++) {
    const v_frame_t *f = &v_frames[i];
    ndp_header h;
    ndp_decoder d;
    size_t n, steps[3] = {1, 7, 100000}, s;
    h.version = 1; h.kind = f->kind; h.flags = f->flags; h.request_id = f->request_id;
    h.command = f->command; h.status = f->status; h.payload_len = 0;
    n = ndp_frame_encode(out, sizeof out, &h, f->payload, f->payload_len, f->has_mac ? f->mac : NULL);
    CHECK(n == f->wire_len && memcmp(out, f->wire, n) == 0, "encode %s", f->name);
    CHECK(ndp_frame_encode(out, n - 1, &h, f->payload, f->payload_len, f->has_mac ? f->mac : NULL) == 0,
          "encode with short buffer must fail (%s)", f->name);
    for (s = 0; s < 3; s++) {
      int frames = 0, rc = -99;
      const ndp_header *dh;
      ndp_decoder_init(&d, buf, sizeof buf, 65536);
      feed_all(&d, f->wire, f->wire_len, steps[s], &frames, &rc);
      CHECK(frames == 1 && rc == NDP_DEC_FRAME, "decode %s step %zu rc=%d", f->name, steps[s], rc);
      if (frames == 1) {
        dh = ndp_decoder_header(&d);
        CHECK(dh->kind == f->kind && dh->flags == f->flags && dh->request_id == f->request_id &&
                  dh->command == f->command && dh->status == f->status && dh->payload_len == f->payload_len,
              "header fields %s", f->name);
        CHECK(f->payload_len == 0 || memcmp(ndp_decoder_payload(&d), f->payload, f->payload_len) == 0,
              "payload %s", f->name);
        CHECK(f->has_mac ? (ndp_decoder_mac(&d) && memcmp(ndp_decoder_mac(&d), f->mac, 16) == 0)
                         : ndp_decoder_mac(&d) == NULL,
              "mac %s", f->name);
      }
    }
  }
  { /* two frames back to back in one buffer; the decoder must stop after the first */
    static uint8_t two[2 * 4096];
    size_t l0 = v_frames[0].wire_len, l1 = v_frames[1].wire_len, used = 0;
    ndp_decoder d;
    int rc;
    memcpy(two, v_frames[0].wire, l0);
    memcpy(two + l0, v_frames[1].wire, l1);
    ndp_decoder_init(&d, buf, sizeof buf, 65536);
    rc = ndp_decoder_feed(&d, two, l0 + l1, &used);
    CHECK(rc == NDP_DEC_FRAME && used == l0, "first of two frames (used=%zu, want %zu)", used, l0);
    CHECK(ndp_decoder_header(&d)->request_id == v_frames[0].request_id, "first frame id");
    ndp_decoder_release(&d);
    rc = ndp_decoder_feed(&d, two + l0, l1, &used);
    CHECK(rc == NDP_DEC_FRAME && used == l1, "second of two frames");
    CHECK(ndp_decoder_header(&d)->request_id == v_frames[1].request_id, "second frame id");
  }
}

static void test_macs(void) {
  int i;
  uint8_t m[NDP_MAC_SIZE];
  for (i = 0; i < V_MACS_N; i++) {
    const v_mac_t *e = &v_macs[i];
    ndp_frame_mac(e->key, 32, e->counter, e->hp, e->hp + NDP_HEADER_SIZE, e->hp_len - NDP_HEADER_SIZE, m);
    CHECK(memcmp(m, e->mac, NDP_MAC_SIZE) == 0, "mac vector %d", i);
  }
  CHECK(ndp_ct_equal("abc", "abc", 3) && !ndp_ct_equal("abc", "abd", 3), "ct_equal");
}

static void test_frame_errors(void) {
  int i;
  static uint8_t buf[NDP_HEADER_SIZE + 65536 + NDP_MAC_SIZE];
  for (i = 0; i < V_FERRS_N; i++) {
    ndp_decoder d;
    size_t used = 0;
    int rc;
    ndp_decoder_init(&d, buf, sizeof buf, v_ferrs[i].max_payload);
    rc = ndp_decoder_feed(&d, v_ferrs[i].wire, v_ferrs[i].wire_len, &used);
    CHECK(rc == NDP_DEC_ERROR && d.error == v_ferrs[i].error, "frame error %s rc=%d err=%d", v_ferrs[i].name, rc,
          d.error);
    rc = ndp_decoder_feed(&d, v_ferrs[i].wire, v_ferrs[i].wire_len, &used);
    CHECK(rc == NDP_DEC_ERROR && used == 0, "error state is sticky (%s)", v_ferrs[i].name);
  }
  { /* a small caller buffer clamps max_payload */
    uint8_t small[NDP_HEADER_SIZE + 8 + NDP_MAC_SIZE];
    ndp_decoder d;
    ndp_decoder_init(&d, small, sizeof small, 65536);
    CHECK(d.max_payload == 8, "max_payload clamped to buffer (%u)", d.max_payload);
  }
}

static void test_names(void) {
  CHECK(strcmp(ndp_command_name(NDP_CMD_HELLO), "HELLO") == 0 && strcmp(ndp_command_name(NDP_CMD_PING), "PING") == 0,
        "command names");
  CHECK(strcmp(ndp_command_name(0x7777), "?") == 0, "unknown command name");
  CHECK(strcmp(ndp_status_name(NDP_OK), "OK") == 0 && strcmp(ndp_status_name(NDP_ST_PATH_INVALID), "PATH_INVALID") == 0 &&
            strcmp(ndp_status_name(NDP_ST_HELLO_REQUIRED), "HELLO_REQUIRED") == 0,
        "status names");
  CHECK(strcmp(ndp_status_name(999), "UNKNOWN") == 0, "unknown status name");
}

static void test_tlv(void) {
  uint8_t b[64];
  ndp_tlv_w w;
  const uint8_t *v;
  size_t l;
  ndp_tlv_w_init(&w, b, sizeof b);
  ndp_tlv_put_u16(&w, 1, 0x1234);
  ndp_tlv_put_str(&w, 2, "hi");
  ndp_tlv_put_u32(&w, 3, 0xAABBCCDDu);
  ndp_tlv_put_u16(&w, 1, 0x9999); /* duplicate tag: first wins */
  CHECK(!w.overflow && ndp_tlv_validate(b, w.len), "tlv validate");
  CHECK(ndp_tlv_find(b, w.len, 1, &v, &l) && l == 2 && ndp_tlv_get_u16(v) == 0x1234, "first occurrence wins");
  CHECK(ndp_tlv_find(b, w.len, 3, &v, &l) && ndp_tlv_get_u32(v) == 0xAABBCCDDu, "u32");
  CHECK(!ndp_tlv_find(b, w.len, 9, &v, &l), "missing tag");
  CHECK(!ndp_tlv_validate(b, w.len - 1), "truncated payload is malformed");
  CHECK(!ndp_tlv_validate(b, 3), "3-byte tail is malformed");
  ndp_tlv_w_init(&w, b, 5);
  ndp_tlv_put_u16(&w, 1, 1);
  CHECK(w.overflow, "overflow detected");
}

static void test_paths(void) {
  int i;
  char out[NDP_PATH_MAX + 1];
  for (i = 0; i < V_PATHS_N; i++) {
    int rc = ndp_path_normalize(v_paths[i].in, v_paths[i].in_len, out, sizeof out);
    if (v_paths[i].ok) {
      CHECK(rc == NDP_OK && strcmp(out, v_paths[i].normalized) == 0, "path %d expected '%s' got rc=%d '%s'", i,
            v_paths[i].normalized, rc, rc == NDP_OK ? out : "");
    } else {
      CHECK(rc == NDP_ST_PATH_INVALID, "path %d must be invalid (rc=%d)", i, rc);
    }
  }
  for (i = 0; i < V_PREFIX_N; i++)
    CHECK(ndp_path_inside(v_prefixes[i].path, v_prefixes[i].root) == v_prefixes[i].inside, "prefix '%s' in '%s'",
          v_prefixes[i].path, v_prefixes[i].root);
}

static void load_list(ndp_pathlist *l, const char *const *src) {
  int k;
  memset(l, 0, sizeof *l);
  for (k = 0; k < 8 && src[k]; k++) CHECK(ndp_pathlist_add(l, src[k]) == NDP_OK, "add %s", src[k]);
}

static void test_policy(void) {
  int i;
  ndp_policy def;
  ndp_policy_init_default(&def);
  CHECK(def.read_roots.count == 1 && def.write_roots.count == 1 && def.never_write.count == 6, "default lists");
  for (i = 0; i < V_POLICY_N; i++) {
    const v_policy_t *e = &v_policies[i];
    ndp_policy p;
    int rc;
    load_list(&p.read_roots, v_cfgs[e->cfg].read_roots);
    load_list(&p.write_roots, v_cfgs[e->cfg].write_roots);
    load_list(&p.never_read, v_cfgs[e->cfg].never_read);
    load_list(&p.never_write, v_cfgs[e->cfg].never_write);
    rc = ndp_policy_check(&p, (ndp_mode)e->mode, e->write, e->path, e->path_len, NULL);
    CHECK(rc == e->status, "policy #%d cfg=%d mode=%d write=%d expected %d got %d", i, e->cfg, e->mode, e->write,
          e->status, rc);
  }
  { /* the built-in default equals the "default" vector config */
    ndp_policy p;
    const uint8_t path[] = "/3ds/nintendo-dev-agent/a.txt";
    char norm[NDP_PATH_MAX + 1];
    ndp_policy_init_default(&p);
    CHECK(ndp_policy_check(&p, NDP_MODE_DEVELOPMENT, 1, path, sizeof path - 1, norm) == NDP_OK &&
              strcmp(norm, "/3ds/nintendo-dev-agent/a.txt") == 0,
          "default policy allows agent folder");
    CHECK(ndp_pathlist_add(&p.read_roots, "relative") == NDP_ST_PATH_INVALID, "list rejects invalid path");
  }
}

static int fixed_nonce(void *ctx, uint8_t *out, size_t n) {
  (void)ctx;
  memcpy(out, v_agent_nonce, n);
  return 0;
}
/* The authenticated dialogues use their own device nonce (v_auth_device_nonce). */
static int fixed_nonce_auth(void *ctx, uint8_t *out, size_t n) {
  (void)ctx;
  memcpy(out, v_auth_device_nonce, n);
  return 0;
}

static void test_dialogues(void) {
  int di;
  static uint8_t dbuf[NDP_HEADER_SIZE + 65536 + NDP_MAC_SIZE], out[4096];
  for (di = 0; di < V_DIALOGUES_N; di++) {
    ndp_agent a;
    ndp_agent_config cfg;
    int si;
    memset(&cfg, 0, sizeof cfg);
    cfg.platform = V_AGENT_PLATFORM;
    cfg.agent_version = V_AGENT_VERSION;
    cfg.mode = NDP_MODE_READ_ONLY;
    cfg.auth = "none";
    cfg.max_frame = V_AGENT_MAXFRAME;
    cfg.random_bytes = fixed_nonce;
    ndp_agent_init(&a, &cfg);
    for (si = 0; si < v_dialogues[di].count; si++) {
      const v_step_t *s = &v_steps[v_dialogues[di].first + si];
      ndp_decoder d;
      size_t used = 0, n;
      int rc;
      ndp_decoder_init(&d, dbuf, sizeof dbuf, 65536);
      rc = ndp_decoder_feed(&d, s->req, s->req_len, &used);
      CHECK(rc == NDP_DEC_FRAME, "dialogue %s step %d: request must decode", v_dialogues[di].name, si);
      if (rc != NDP_DEC_FRAME) continue;
      n = ndp_agent_handle(&a, ndp_decoder_header(&d), ndp_decoder_payload(&d), out, sizeof out);
      CHECK(n == s->res_len && memcmp(out, s->res, n) == 0, "dialogue %s step %d: response mismatch (len %zu vs %zu)",
            v_dialogues[di].name, si, n, s->res_len);
    }
  }
  { /* a too-small output buffer yields 0, never an overflow */
    ndp_agent a;
    ndp_agent_config cfg;
    uint8_t tiny[10];
    ndp_header h = {1, NDP_KIND_REQ, 0, 1, 0x7777, 0, 0};
    memset(&cfg, 0, sizeof cfg);
    cfg.platform = "host"; cfg.agent_version = "0"; cfg.auth = "none";
    ndp_agent_init(&a, &cfg);
    CHECK(ndp_agent_handle(&a, &h, NULL, tiny, sizeof tiny) == 0, "tiny output buffer");
  }
}

/* ---------------------------------------------------------------- pairing / authentication */
static void test_auth_primitives(void) {
  int i;
  uint8_t code[NDP_CODE_BYTES], psk[32], id[4], out[32];
  char text[NDP_CODE_TEXT];
  for (i = 0; i < V_KDF_N; i++) {
    const v_kdf_t *k = &v_kdfs[i];
    ndp_code_encode(k->code, text);
    CHECK(strcmp(text, k->code_text) == 0, "code text %d: %s vs %s", i, text, k->code_text);
    CHECK(ndp_code_decode(k->code_text, code) == 0 && memcmp(code, k->code, NDP_CODE_BYTES) == 0, "code round trip %d", i);
    ndp_derive_psk(k->code, psk);
    CHECK(memcmp(psk, k->psk, 32) == 0, "psk %d", i);
    ndp_key_id(psk, id);
    CHECK(memcmp(id, k->key_id, 4) == 0, "key id %d", i);
    ndp_proof(psk, "pair", k->cn, k->dn, (const uint8_t *)k->label, strlen(k->label), out);
    CHECK(memcmp(out, k->pair_proof, 32) == 0, "pair proof %d", i);
    ndp_proof(psk, "auth", k->cn, k->dn, NULL, 0, out);
    CHECK(memcmp(out, k->auth_proof, 32) == 0, "auth proof %d", i);
    ndp_session_key(psk, k->cn, k->dn, out);
    CHECK(memcmp(out, k->session, 32) == 0, "session key %d", i);
  }
  for (i = 0; i < V_CODEDEC_N; i++) {
    int rc = ndp_code_decode(v_codedecs[i].text, code);
    if (v_codedecs[i].ok) CHECK(rc == 0 && memcmp(code, v_codedecs[i].code, NDP_CODE_BYTES) == 0, "decode '%s'", v_codedecs[i].text);
    else CHECK(rc != 0, "decode '%s' must fail", v_codedecs[i].text);
  }
}

static void test_keystore(void) {
  ndp_keystore ks, back;
  uint8_t buf[NDP_KEYSTORE_MAX_BYTES], psk[32];
  size_t n, i;
  int j;
  ndp_keystore_clear(&ks);
  memset(ks.device_id, 0x42, 16);
  ks.has_device_id = 1;
  for (j = 0; j < NDP_MAX_KEYS; j++) {
    char lab[8];
    memset(psk, j + 1, 32);
    snprintf(lab, sizeof lab, "pc%d", j);
    CHECK(ndp_keystore_add(&ks, psk, lab) == NDP_OK, "add %d", j);
  }
  memset(psk, 9, 32);
  CHECK(ndp_keystore_add(&ks, psk, "extra") == NDP_ST_NO_SPACE, "store full");
  memset(psk, 1, 32);
  CHECK(ndp_keystore_add(&ks, psk, "dup") == NDP_OK && ks.count == NDP_MAX_KEYS, "an identical key is a no-op");
  n = ndp_keystore_serialize(&ks, buf, sizeof buf);
  CHECK(n == 24 + NDP_MAX_KEYS * 52 + 32, "serialized size %zu", n);
  CHECK(ndp_keystore_serialize(&ks, buf, n - 1) == 0, "too small buffer");
  CHECK(ndp_keystore_parse(&back, buf, n) == 0 && back.count == NDP_MAX_KEYS && memcmp(back.device_id, ks.device_id, 16) == 0 &&
            strcmp(back.keys[2].label, "pc2") == 0 && memcmp(back.keys[3].psk, ks.keys[3].psk, 32) == 0, "round trip");
  for (i = 0; i < n; i++) { /* any single flipped byte is detected */
    uint8_t save = buf[i];
    buf[i] ^= 0x01;
    CHECK(ndp_keystore_parse(&back, buf, n) != 0 && back.count == 0, "corruption at byte %zu detected", i);
    buf[i] = save;
  }
  CHECK(ndp_keystore_parse(&back, buf, n - 1) != 0, "truncated");
  CHECK(ndp_keystore_parse(&back, buf, 0) != 0, "empty");
  ndp_keystore_clear(&ks);
  n = ndp_keystore_serialize(&ks, buf, sizeof buf);
  CHECK(n == 24 + 32 && ndp_keystore_parse(&back, buf, n) == 0 && back.count == 0, "empty store round trip");
}

static int fail_rng(void *ctx, uint8_t *out, size_t n) { (void)ctx; memset(out, 0, n); return -1; }

static void test_auth_dialogues(void) {
  int di;
  static uint8_t dbuf[NDP_HEADER_SIZE + 65536 + NDP_MAC_SIZE], out[NDP_HEADER_SIZE + 65536 + NDP_MAC_SIZE];
  for (di = 0; di < V_ADLG_N; di++) {
    const v_adlg_t *d = &v_adlgs[di];
    ndp_agent a;
    ndp_agent_config cfg;
    ndp_keystore ks;
    ndp_pairing pairing;
    int si, k, closed = 0;
    memset(&cfg, 0, sizeof cfg);
    ndp_keystore_clear(&ks);
    memcpy(ks.device_id, v_auth_device_id, 16);
    ks.has_device_id = 1;
    for (k = 0; k < d->key_count; k++) ndp_keystore_add(&ks, v_akeys[d->key_first + k].psk, v_akeys[d->key_first + k].label);
    memset(&pairing, 0, sizeof pairing);
    pairing.active = d->pairing_open;
    if (d->pairing_open) memcpy(pairing.code, d->code, NDP_CODE_BYTES);
    cfg.platform = V_AGENT_PLATFORM; cfg.agent_version = V_AGENT_VERSION; cfg.mode = NDP_MODE_READ_ONLY;
    cfg.auth = "required"; cfg.max_frame = V_AGENT_MAXFRAME;
    cfg.random_bytes = d->rng_fail ? fail_rng : fixed_nonce_auth;
    cfg.keys = &ks; cfg.pairing = &pairing;
    ndp_agent_init(&a, &cfg);
    for (si = 0; si < d->count && !closed; si++) {
      const v_astep_t *s = &v_asteps[d->first + si];
      ndp_decoder dec;
      size_t used = 0, n;
      int rc;
      ndp_decoder_init(&dec, dbuf, sizeof dbuf, 65536);
      rc = ndp_decoder_feed(&dec, s->req, s->req_len, &used);
      CHECK(rc == NDP_DEC_FRAME, "auth dialogue %s step %d: request must decode", d->name, si);
      if (rc != NDP_DEC_FRAME) break;
      n = ndp_agent_handle_frame(&a, ndp_decoder_header(&dec), ndp_decoder_payload(&dec), ndp_decoder_mac(&dec), out, sizeof out);
      if (s->close) {
        CHECK(n == NDP_CLOSE, "auth dialogue %s step %d: the connection must be closed (got %zu)", d->name, si, n);
        closed = 1;
      } else {
        CHECK(n == s->res_len && n != NDP_CLOSE && memcmp(out, s->res, n) == 0, "auth dialogue %s step %d: response mismatch (len %zu vs %zu)", d->name, si, n, s->res_len);
      }
    }
    CHECK(ks.count == d->after_count, "auth dialogue %s: %d keys stored, want %d", d->name, ks.count, d->after_count);
    for (k = 0; k < d->after_count && k < ks.count; k++)
      CHECK(memcmp(ks.keys[k].psk, v_aafter[di][k], 32) == 0, "auth dialogue %s: stored key %d", d->name, k);
    CHECK(pairing.active == d->pairing_open_after, "auth dialogue %s: pairing window %d, want %d", d->name, pairing.active, d->pairing_open_after);
  }
}


int main(void) {
  test_sha256();
  test_hmac();
  test_frames();
  test_macs();
  test_frame_errors();
  test_names();
  test_tlv();
  test_paths();
  test_policy();
  test_dialogues();
  test_auth_primitives();
  test_keystore();
  test_auth_dialogues();
  printf("%d checks, %d failed\n", g_checks, g_fail);
  return g_fail ? 1 : 0;
}
