#!/usr/bin/env python3
"""Builds the console's web page: web/index.html with web/app.css and web/js/*.js inlined (order given by web/js/ORDER),
gzip-compressed (deterministic), emitted as agent/web/ndp_web_assets_data.c for the 3DS and host agents.
`--check` only verifies that the committed file is up to date."""
import gzip, hashlib, io, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "web")
OUT_C = os.path.join(ROOT, "agent", "web", "ndp_web_assets_data.c")


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def build_html():
    html = read(os.path.join(WEB, "index.html"))
    css = read(os.path.join(WEB, "app.css"))
    order_file = os.path.join(WEB, "js", "ORDER")
    names = [l.strip() for l in read(order_file).splitlines() if l.strip() and not l.startswith("#")] if os.path.exists(order_file) else ["main.js"]
    js = "\n".join("/* ---- %s ---- */\n%s" % (n, read(os.path.join(WEB, "js", n))) for n in names)
    assert "</script" not in js.lower().replace("<\\/script", ""), "the script must not contain a closing script tag"
    html = html.replace("/*__CSS__*/", css).replace("/*__JS__*/", js)
    return html.encode("utf-8")


def gz(data):
    buf = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=buf, compresslevel=9, mtime=0) as f:
        f.write(data)
    return buf.getvalue()


def emit(html, z):
    version = hashlib.sha256(html).hexdigest()[:12]
    lines = ["/* GENERATED by scripts/build-web.py from web/ -- do not edit. */", "#include <stddef.h>", "#include <stdint.h>", "",
             "const char ndp_web_version[] = \"%s\";" % version, "const size_t ndp_web_index_gz_len = %d;" % len(z),
             "const uint8_t ndp_web_index_gz[%d] = {" % len(z)]
    for i in range(0, len(z), 16):
        lines.append("  " + ", ".join("0x%02x" % b for b in z[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n", version


def main():
    html = build_html()
    z = gz(html)
    text, version = emit(html, z)
    if "--check" in sys.argv:
        cur = read(OUT_C) if os.path.exists(OUT_C) else ""
        if cur != text:
            print("web page changed after regeneration - run scripts/build-web.py and commit agent/web/", file=sys.stderr)
            sys.exit(1)
        print("web assets up to date (%d bytes html, %d bytes gzip, %s)" % (len(html), len(z), version))
        return
    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write(text)
    with open(os.path.join(ROOT, "build-web-index.html"), "wb") as f:
        f.write(html)  # unpacked copy for browser debugging (git-ignored)
    print("web page: %d bytes html -> %d bytes gzip (%s)" % (len(html), len(z), version))


if __name__ == "__main__":
    main()
