// Verifies the TypeScript implementation against docs/protocol/test-vectors/vectors.json,
// generated by an independent implementation (generate.py). The C tests use the same data.
import { strict as assert } from "node:assert";
import { createHash, createHmac } from "node:crypto";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import {
  Flag, FrameDecoder, HEADER_SIZE, Kind, NdpProtocolError, PathInvalidError, Status, checkPolicy, isChildVisible, isTraversable, decodeHeader,
  encodeFrame, frameMac, makePolicy, normalizePath, parseTlv, pathInside, statusName, type Mode,
} from "../src/index.ts";

const vectorsPath = fileURLToPath(new URL("../../../../docs/protocol/test-vectors/vectors.json", import.meta.url));
const V = JSON.parse(readFileSync(vectorsPath, "utf8"));
const hex = (h: string) => new Uint8Array(Buffer.from(h, "hex"));
const toHex = (b: Uint8Array) => Buffer.from(b).toString("hex");

test("constants match the generator", () => {
  assert.deepEqual(V.constants.status, Status);
  assert.deepEqual(V.constants.kind, Kind);
});

test("sha256 / hmac vectors agree with node:crypto (sanity for the vector file itself)", () => {
  for (const e of V.sha256) assert.equal(createHash("sha256").update(hex(e.msg_hex)).digest("hex"), e.digest_hex);
  for (const e of V.hmac_sha256)
    assert.equal(createHmac("sha256", hex(e.key_hex)).update(hex(e.msg_hex)).digest("hex"), e.mac_hex);
});

for (const f of V.frames) {
  test(`frame ${f.name}: encode is byte-exact`, () => {
    const out = encodeFrame({
      kind: f.kind, flags: f.flags & ~Flag.MAC, requestId: f.request_id, command: f.command, status: f.status,
      payload: hex(f.payload_hex), ...(f.mac_hex ? { mac: hex(f.mac_hex) } : {}),
    });
    assert.equal(toHex(out), f.wire_hex);
  });

  for (const step of [1, 7, 1 << 20]) {
    test(`frame ${f.name}: decode with ${step}-byte chunks`, () => {
      const wire = hex(f.wire_hex);
      const dec = new FrameDecoder(65536);
      const frames = [];
      for (let i = 0; i < wire.length; i += step) frames.push(...dec.push(wire.subarray(i, i + step)));
      assert.equal(frames.length, 1);
      const fr = frames[0]!;
      assert.equal(fr.header.kind, f.kind);
      assert.equal(fr.header.flags, f.flags);
      assert.equal(fr.header.requestId, f.request_id);
      assert.equal(fr.header.command, f.command);
      assert.equal(fr.header.status, f.status);
      assert.equal(toHex(fr.payload), f.payload_hex);
      assert.equal(fr.mac ? toHex(fr.mac) : null, f.mac_hex);
    });
  }
}

test("two frames in one chunk", () => {
  const a = hex(V.frames[0].wire_hex);
  const b = hex(V.frames[1].wire_hex);
  const both = new Uint8Array(a.length + b.length);
  both.set(a, 0);
  both.set(b, a.length);
  const frames = new FrameDecoder(65536).push(both);
  assert.deepEqual(frames.map((x) => x.header.requestId), [V.frames[0].request_id, V.frames[1].request_id]);
});

for (const e of V.frame_errors) {
  test(`frame error ${e.name}`, () => {
    const dec = new FrameDecoder(e.max_payload);
    assert.throws(
      () => dec.push(hex(e.wire_hex)),
      (err: unknown) => err instanceof NdpProtocolError && err.status === Status[e.error as keyof typeof Status],
    );
    assert.throws(() => dec.push(new Uint8Array(0)), NdpProtocolError, "error state is sticky");
  });
}

test("decodeHeader validates magic and flags", () => {
  const good = hex(V.frames[0].wire_hex).subarray(0, HEADER_SIZE);
  assert.equal(decodeHeader(good).command, 1);
  assert.throws(() => decodeHeader(good.subarray(0, 19)), NdpProtocolError);
});

for (const e of V.mac) {
  test(`mac ${e.name} (counter ${e.counter})`, () => {
    const hp = hex(e.header_and_payload_hex);
    const out = frameMac(hex(e.key_hex), BigInt(e.counter), hp.subarray(0, HEADER_SIZE), hp.subarray(HEADER_SIZE));
    assert.equal(toHex(out), e.mac_hex);
  });
}

test("paths", () => {
  for (const p of V.paths) {
    const input = hex(p.input_hex);
    if (p.ok) assert.equal(normalizePath(input), p.normalized, `input ${p.input_hex}`);
    else assert.throws(() => normalizePath(input), PathInvalidError, `input ${p.input_hex}`);
  }
});

test("prefix comparison", () => {
  for (const e of V.prefix) assert.equal(pathInside(e.path, e.root), e.inside, `${e.path} in ${e.root}`);
});

test("policy", () => {
  const cfgs = Object.fromEntries(
    Object.entries(V.policy_configs as Record<string, any>).map(([k, c]) => [
      k,
      makePolicy({ readRoots: c.read_roots, writeRoots: c.write_roots, neverRead: c.never_read, neverWrite: c.never_write, writeExcept: c.write_except ?? [] }),
    ]),
  );
  for (const e of V.policy) {
    const d = checkPolicy(cfgs[e.config]!, e.mode as Mode, e.op, hex(e.path_hex));
    assert.equal(d.status, e.status, `${e.config}/${e.mode}/${e.op}/${e.path_hex}`);
    assert.equal(d.code, e.status_code);
  }
});

test("statusName", () => {
  assert.equal(statusName(4), "PROTECTED_PATH");
  assert.equal(statusName(999), "UNKNOWN_999");
});

test("tlv: first occurrence wins, overrun is malformed", () => {
  const good = hex("010002003412" + "010002009999" + "03000000"); // tag1=0x1234, tag1=0x9999, tag3 (empty)
  const m = parseTlv(good);
  assert.equal(m.u16(1), 0x1234);
  assert.equal(m.first(3)?.length, 0);
  assert.throws(() => parseTlv(hex("010005003412")), NdpProtocolError);
  assert.throws(() => parseTlv(hex("01000200341201")), NdpProtocolError);
});

test("traversal (spec §11.1) agrees with the reference", () => {
  const cfgs = Object.fromEntries(
    Object.entries(V.policy_configs as Record<string, any>).map(([k, c]) => [
      k, makePolicy({ readRoots: c.read_roots, writeRoots: c.write_roots, neverRead: c.never_read, neverWrite: c.never_write, writeExcept: c.write_except ?? [] }),
    ]),
  );
  assert.ok(V.traverse.length > 40);
  for (const e of V.traverse) {
    assert.equal(isTraversable(cfgs[e.config]!, e.path), e.traversable, `${e.config} ${e.path}`);
    assert.equal(isChildVisible(cfgs[e.config]!, e.path), e.visible, `${e.config} ${e.path}`);
  }
});
